// Generated by CoffeeScript 1.6.3
/*
!
mathjax-lazyload 1.0.0
Alberto Leal (c) 2013 MIT License
*/

(function(window) {
  requirejs.config({
    enforceDefine: true,
    urlArgs: 'bust=' + (new Date()).getTime(),
    paths: {
      'lodash': 'libs/lodash.custom',
      'async': 'libs/async'
    },
    shim: {
      lodash: {
        exports: '_'
      },
      "app": {
        deps: ['lodash', 'async'],
        exports: "_LazyLoad"
      }
    }
  });
  require(["app"], function(_LazyLoad) {
    _LazyLoad.get(window);
  });
})(window || (1, eval)("this"));
